# Generated by Django 4.2.4 on 2023-08-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('sn', 'sunny'), ('cl', 'cloudy'), ('wn', 'windy'), ('rn', 'rainy'), ('st', 'stormy')], max_length=3)),
            ],
        ),
    ]
