CREATE DATABASE bootcamp;

\c bootcamp

CREATE TABLE students (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
  birth_date DATE NOT NULL
);

INSERT INTO items 
(first_name, last_name, birth_date)

VALUES 
('Marc', 'Benichou', TO_DATE('02/11/1998', 'DD/MM/YYYY')),
('Yoan', 'Cohen', TO_DATE('03/12/2010', 'DD/MM/YYYY')),
('Lea', 'Benichou', TO_DATE('27/07/1987', 'DD/MM/YYYY')),
('Amelia', 'Dux', TO_DATE('07/04/1996', 'DD/MM/YYYY')),
('David', 'Grez', TO_DATE('14/06/2003', 'DD/MM/YYYY')),
('Omer', 'Simpson', TO_DATE('03/10/1980', 'DD/MM/YYYY'))

-- OUTPUT

SELECT * FROM STUDENTS

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS WHERE ID = 2

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS WHERE LAST_NAME ILIKE 'Benichou' AND FIRST_NAME ILIKE 'MARC'

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS WHERE LAST_NAME ILIKE 'Benichou' OR FIRST_NAME ILIKE 'MARC'

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS WHERE FIRST_NAME ILIKE '%a%'

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS WHERE FIRST_NAME ILIKE 'a%'

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS WHERE FIRST_NAME ILIKE '%a'

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS WHERE SUBSTRING(first_name, LENGTH(first_name) - 1, 1) = 'a';

SELECT FIRST_NAME, LAST_NAME FROM STUDENTS WHERE ID = 1 or ID = 3

SELECT * FROM STUDENTS WHERE birth_date >= DATE '2000-01-01';